#!/usr/bin/env php
<?php
defined('QZZM_ROOT') or define('QZZM_ROOT', realpath(getcwd()));
$autoload = QZZM_ROOT . '/vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
} else {
    die("require composer autoload.php fail\n");
}
$args = $argv;
array_shift($args);
$result = \qzzm\command\Runner::getInstance()->run($args);
if (!empty($result)) {
    echo $result . "\n";
}


